showの画面をindexから見れるようにしました
nextbeat-dev/summer-intern-0809-B pull request #9
Opened 2019-08-10 11:23 UTC by hdknis

2019-08-10 11:30 UTC, tan1p0p requested changes

2019-08-10 11:30 UTC, tan1p0p commented on conf/routes
> +GET  /facility/:id                   controllers.facility.FacilityController.show(id: Long)
インデントが少し気になるかもです！

2019-08-11 00:45 UTC, raru-ex commented on app/controllers/facility/FacilityController.scala
> +      facilityOp  <- facilityDao.get(id)
`Some(facility) <- facilityDat.get(id)` にしちゃっていいですよ。
本来Option型はちゃんと処理したいのですが、そもそもベースになってるデータがないときにはそのまま404とかにしてしまって問題ないためです。

慣習として Option.getで直接値を取得しようとする書き方はよくないので、正直あまり変わらないのですが上記の方がまだいいかなと。
弊社のプロジェクトでもそういう形で書いてます。

2019-08-11 00:45 UTC, raru-ex commented on app/controllers/facility/FacilityController.scala
> +      locOp      <- daoLocation.get(facilityOp.get.locationId)
ここも

2019-08-11 00:51 UTC, raru-ex commented on app/model/site/facility/FacilityShow.scala
> +  facility: Option[Facility]
Controllerの修正に伴ってここはOption外してください。

2019-08-11 00:51 UTC, raru-ex commented on app/views/site/facility/show/_02_slide.scala.html
> +      @for(facility <- vv.facility.get.imagePaths.split(",")) {
`@for(facility <- vv.facility.get.imagePaths.split(",")) {`
よりは
`@for(imagePath <- vv.facility.get.imagePaths.split(",")) {`
とかの方が適切です。
変数はそれを見たときに、そこに何が入ってるかわかるように宣言した方が良いです。

2019-08-11 00:51 UTC, raru-ex commented on app/views/site/facility/list/_List.scala.html
> +        <a href="../facility/@facility.id">
`<a href="@controllers.facility.FacilityController.show(facility.id)">`
みたいな感じでかけると思います。
この方がroutes変わった際にコンパイルエラーにできるのとurlも環境に合わせて作られて便利なので、こんなかんじで

2019-08-11 03:03 UTC, merged